version: 2.1

# Parameters
parameters:
  newname:
    type: string
    default: Pako

# Comandos reutilizables
commands:
  # Nombre del comando
  say_date:
    # Parametrizar comandos
    parameters:
      # Nombre del parametro del comando
      timenumber:
        type: integer
        default: 5
    steps:
      - run: date && sleep 10

  say_hi:
    parameters:
      timenumber:
        type: integer
        default: 5
    steps:
      - run: echo << parameters.timenumber >>

jobs:
  hello:
    docker:
      - image: ubuntu:latest
    steps:
      # Llamada al comando por nombre
      - say_date
      - run: echo Hello
      - say_date

  bye:
    docker:
      - image: cimg/base:stable
    steps:
      # Variable a nivel pipeline
      - run: echo Hello << pipeline.parameters.newname >>
      - say_hi:
          # Cambiar el parametro por defecto
          timenumber: 10

workflows:
  say:
    jobs:
      - hello:
          name: say_hello
      - bye:
          name: say_bye
          requires:
            - say_hello
